const data = {
    equipos: [
      {
        id: 0,
        nombre: "Real Madrid",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 35,
        champions_league: 14,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/7/70/RealMadrid.png",
      },
      {
        id:1,
        nombre: "Real Betis",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 1,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_betis_logo.svg/1200px-Real_betis_logo.svg.png",
      },
      {
        id:2,
        nombre: "Barcelona",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 27,
        champions_league: 5,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/1200px-FC_Barcelona_%28crest%29.svg.png",
      },
      {
        id:3,
        nombre: "Manchester United",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 20,
        champions_league: 3,
        imagen: "https://upload.wikimedia.org/wikipedia/an/7/7a/Manchester_United_FC_crest.svg",
      },
      {
        id:4,
        nombre: "Manchester City",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 9,
        champions_league: 1,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
      },
      {
        id:5,
        nombre: "Atletico de Madrid",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 11,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Atletico_Madrid_2017_logo.svg/1200px-Atletico_Madrid_2017_logo.svg.png",
      },
      {
        id:6,
        nombre: "Valencia",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 6,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Valenciacf.svg/1200px-Valenciacf.svg.png",
      },
      {
        id:7,
        nombre: "Athletic Club",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 8,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Club_Athletic_Bilbao_logo.svg/1200px-Club_Athletic_Bilbao_logo.svg.png",
      },
      {
        id:8,
        nombre: "Liverpool",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 19,
        champions_league: 6,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png",
      },
      {
        id:9,
        nombre: "Chelsea",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 6,
        champions_league: 2,
        imagen: "https://upload.wikimedia.org/wikipedia/an/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png",
      },
      {
        id:10,
        nombre: "Arsenal",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 13,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
      },
      {
        id:11,
        nombre: "Milan",
        pais: "Italia",
        liga: "Serie A",
        ligas_totales: 16,
        champions_league: 7,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1200px-Logo_of_AC_Milan.svg.png",
      },
    ],
  };
  
  export default data;
  