const data = {
    jugadores: [
      {
        idj:1,
        nombre: "Cristiano Ronaldo",
        pais: "Portugal",
        equipo_actual: "Al-Nassr",
        goles_totales: 880,
        imagen: "./imgjugador/cristiano.png",
      },
      {
        idj:2,
        nombre: "Leo Messi",
        pais: "Argentina",
        equipo_actual: "Inter de Miami",
        goles_totales: 835,
        imagen: "./imgjugador/leomessi.jpg",
      },
      {
        idj:3,
        nombre: "Kylian Mbappe",
        pais: "Francia",
        equipo_actual: "PSG",
        goles_totales: 324,
        imagen: "./imgjugador/kylianmbappe.jpg",
      },
      {
        idj:4,
        nombre: "Antoine Griezmann",
        pais: "Francia",
        equipo_actual: "Atletico de Madrid",
        goles_totales: 310,
        imagen: "./imgjugador/antoinegriezmann.jpg",
      },
      {
        idj:5,
        nombre: "Mohamed Salah",
        pais: "Egipto",
        equipo_actual: "Liverpool",
        goles_totales: 341,
        imagen: "./imgjugador/mohamedsalah.jpg",
      },
      {
        idj:6,
        nombre: "Heung-Min Son",
        pais: "Corea del Sur",
        equipo_actual: "Tottenham",
        goles_totales: 271,
        imagen: "./imgjugador/son.jpg",
      },
      {
        idj:7,
        nombre: "Harry Kane",
        pais: "Inglaterra",
        equipo_actual: "Bayern de Munich",
        goles_totales: 412,
        imagen: "./imgjugador/kane.jpg",
      },
      {
        idj:8,
        nombre: "Neymar Jr",
        pais: "Brasil",
        equipo_actual: "Al-Hilal",
        goles_totales: 454,
        imagen: "./imgjugador/neymar.jpg",
      },
      {
        idj:9,
        nombre: "Karim Benzema",
        pais: "Francia",
        equipo_actual: "Al-Ittihad",
        goles_totales: 473,
        imagen: "./imgjugador/benzema.jpg",
      },
      {
        idj:10,
        nombre: "Erling Haaland",
        pais: "Noruega",
        equipo_actual: "Manchester City",
        goles_totales: 299,
        imagen: "./imgjugador/haaland.jpg",
      },
      {
        idj:11,
        nombre: "Rodri",
        pais: "España",
        equipo_actual: "Manchester City",
        goles_totales: 31,
        imagen: "./imgjugador/rodri.jpg",
      },
      {
        idj:12,
        nombre: "Luis Suarez",
        pais: "Uruguay",
        equipo_actual: "Inter de Miami",
        goles_totales: 556,
        imagen: "./imgjugador/suarez.jpg",
      },
      {
        idj:13,
        nombre: "Robert Lewandowski",
        pais: "Polonia",
        equipo_actual: "Barcelona",
        goles_totales: 636,
        imagen: "./imgjugador/lewandowski.jpg",
      },
      {
        idj:14,
        nombre: "Vinicius Junior",
        pais: "Brasil",
        equipo_actual: "Real Madrid",
        goles_totales: 98,
        imagen: "./imgjugador/vini.jpg",
      },
      {
        idj:15,
        nombre: "Olivier Giroud",
        pais: "Francia",
        equipo_actual: "Milan",
        goles_totales: 320,
        imagen: "./imgjugador/giroud.jpg",
      },

    ],
    equipos: [
      {
        id: 1,
        nombre: "Real Madrid",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 35,
        champions_league: 14,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/7/70/RealMadrid.png",
      },
      {
        id:2,
        nombre: "Real Betis",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 1,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_betis_logo.svg/1200px-Real_betis_logo.svg.png",
      },
      {
        id:3,
        nombre: "Barcelona",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 27,
        champions_league: 5,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/1200px-FC_Barcelona_%28crest%29.svg.png",
      },
      {
        id:4,
        nombre: "Manchester United",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 20,
        champions_league: 3,
        imagen: "https://upload.wikimedia.org/wikipedia/an/7/7a/Manchester_United_FC_crest.svg",
      },
      {
        id:5,
        nombre: "Manchester City",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 9,
        champions_league: 1,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
      },
      {
        id:6,
        nombre: "Atletico de Madrid",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 11,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Atletico_Madrid_2017_logo.svg/1200px-Atletico_Madrid_2017_logo.svg.png",
      },
      {
        id:7,
        nombre: "Valencia",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 6,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Valenciacf.svg/1200px-Valenciacf.svg.png",
      },
      {
        id:8,
        nombre: "Athletic Club",
        pais: "España",
        liga: "LaLiga",
        ligas_totales: 8,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Club_Athletic_Bilbao_logo.svg/1200px-Club_Athletic_Bilbao_logo.svg.png",
      },
      {
        id:9,
        nombre: "Liverpool",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 19,
        champions_league: 6,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png",
      },
      {
        id:10,
        nombre: "Chelsea",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 6,
        champions_league: 2,
        imagen: "https://upload.wikimedia.org/wikipedia/an/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png",
      },
      {
        id:11,
        nombre: "Arsenal",
        pais: "Inglaterra",
        liga: "Premier League",
        ligas_totales: 13,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
      },
      {
        id:12,
        nombre: "Milan",
        pais: "Italia",
        liga: "Serie A",
        ligas_totales: 16,
        champions_league: 7,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1200px-Logo_of_AC_Milan.svg.png",
      },
      {
        id:13,
        nombre: "Inter Milan",
        pais: "Italia",
        liga: "Serie A",
        ligas_totales: 17,
        champions_league: 3,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/1200px-FC_Internazionale_Milano_2021.svg.png",
      },
      {
        id:14,
        nombre: "Juventus",
        pais: "Italia",
        liga: "Serie A",
        ligas_totales: 34,
        champions_league: 2,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/5/51/Juventus_FC_2017_logo.png",
      },
      {
        id:15,
        nombre: "Bayern Munich",
        pais: "Alemania",
        liga: "Bundesliga",
        ligas_totales: 32,
        champions_league: 6,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/2048px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
      },
      {
        id:16,
        nombre: "Borussia Dortmund",
        pais: "Alemania",
        liga: "Bundesliga",
        ligas_totales: 5,
        champions_league: 1,
        imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/2048px-Borussia_Dortmund_logo.svg.png",
      },
      {
        id:17,
        nombre: "PSG",
        pais: "Francia",
        liga: "Ligue 1",
        ligas_totales: 11,
        champions_league: 0,
        imagen: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/1200px-Paris_Saint-Germain_F.C..svg.png",
      },


    ],
  };
  
  export default data;
  